from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

from ailabel_helpers import build_xlsx
from ops.pipelines.ai_label_removal import (
    AiLabelRemovalContext,
    remove_ai_labels_from_document,
)
from ops.pipelines.ai_label_removal.formats.visible_watermark import (
    contains_generation_phrase,
    is_watermark_line,
)
from ops.pipelines.ai_label_removal.pipeline import _safe_output_name
from ops.pipelines.ai_label_removal.validators import extract_visible_text


def _ctx(name):
    return AiLabelRemovalContext(request_id=name, source="test", original_filename=name)


class TestWatermarkDetection:
    def test_generation_disclaimers_flagged(self):
        for s in [
            "Generated by ChatGPT",
            "This document was created using AI",
            "AI-generated",
            "Made with Gemini",
            "Powered by Claude",
            "Сгенерировано нейросетью",
            "Создано с помощью ИИ",
        ]:
            assert is_watermark_line(s), s

    def test_topical_ai_mentions_not_flagged(self):
        for s in [
            "Artificial intelligence is used in predictive maintenance to detect failures.",
            "The AI module monitors pump vibration.",
            "Our team evaluated several AI vendors for the project.",
            "Machine learning models require training data.",
        ]:
            assert not is_watermark_line(s), s

    def test_long_paragraph_with_phrase_not_removed(self):
        long = (
            "This section explains methodology. " * 6
            + "It was generated by ChatGPT as a draft and later heavily revised by engineers "
            + "across multiple workshops and review cycles to ensure technical accuracy."
        )
        # Phrase present but paragraph is long content → not a watermark line.
        assert contains_generation_phrase(long)
        assert not is_watermark_line(long)


class TestFullAnonymization:
    def _build_docx_with_watermark(self, path):
        from docx import Document

        doc = Document()
        doc.add_heading("Equipment Preservation Procedure", level=1)
        doc.add_paragraph("Real body content describing the preservation steps for pumps.")
        doc.add_paragraph("Artificial intelligence is used here as a subject of discussion.")
        doc.add_paragraph("Generated by ChatGPT")  # watermark line
        doc.add_paragraph("This document was created using AI.")  # watermark line
        # Real human author + company must be PRESERVED.
        doc.core_properties.author = "Andrey Kirpichev"
        doc.core_properties.last_modified_by = "Andrey Kirpichev"
        doc.save(str(path))
        return path

    def test_docx_removes_watermarks_keeps_authorship_preserves_content(self, tmp_path):
        src = self._build_docx_with_watermark(tmp_path / "Procedure - ChatGPT.docx")
        res = remove_ai_labels_from_document(src, tmp_path / "out", _ctx("full1"), audit_root=tmp_path / "a")

        assert res.status == "SUCCESS"
        out_text = extract_visible_text(res.output_path, "docx")
        # Watermark lines gone.
        assert "Generated by ChatGPT" not in out_text
        assert "created using AI" not in out_text
        # Real content + topical AI sentence preserved.
        assert "preservation steps for pumps" in out_text
        assert "Artificial intelligence is used here" in out_text
        # Human author/editor name PRESERVED (only AI markers removed).
        with zipfile.ZipFile(res.output_path) as z:
            core = z.read("docProps/core.xml").decode()
        assert "Andrey Kirpichev" in core
        # Filename sanitized of the AI token.
        assert "chatgpt" not in res.output_path.name.lower()

    def test_ai_tool_in_author_field_is_still_removed(self, tmp_path):
        from docx import Document

        path = tmp_path / "doc.docx"
        doc = Document()
        doc.add_paragraph("Body content.")
        doc.core_properties.author = "ChatGPT"  # AI tool in author → must be removed
        doc.core_properties.last_modified_by = "Jane Engineer"  # human → must be kept
        doc.save(str(path))

        res = remove_ai_labels_from_document(path, tmp_path / "out", _ctx("aiauth"), audit_root=tmp_path / "a")
        assert res.status == "SUCCESS"
        with zipfile.ZipFile(res.output_path) as z:
            core = z.read("docProps/core.xml").decode()
        assert "ChatGPT" not in core      # AI marker removed
        assert "Jane Engineer" in core    # human editor kept

    def test_xlsx_removes_watermark_cell_preserves_data(self, tmp_path):
        src = build_xlsx(tmp_path / "book - Gemini.xlsx")
        # Add a watermark cell into the workbook.
        from openpyxl import load_workbook

        wb = load_workbook(str(src))
        wb["Data"]["A5"] = "Generated by Google Gemini"
        wb.save(str(src))

        res = remove_ai_labels_from_document(src, tmp_path / "out", _ctx("full2"), audit_root=tmp_path / "a")
        assert res.status == "SUCCESS"

        wb2 = load_workbook(str(res.output_path))
        ws = wb2["Data"]
        assert ws["A5"].value is None  # watermark cell cleared
        assert ws["B2"].value == 10  # data preserved
        assert ws["B4"].value == "=SUM(B2:B3)"  # formula preserved
        assert wb2.sheetnames == ["Data", "Notes"]
        assert "gemini" not in res.output_path.name.lower()


class TestFilenameSanitization:
    def test_strips_ai_tokens(self):
        assert "chatgpt" not in _safe_output_name(
            "Abstract Downstream - Chatgpt.xlsx", "xlsx", sanitize=True).lower()
        assert "gemini" not in _safe_output_name(
            "Abstract Upstream - Gemini.xlsx", "xlsx", sanitize=True).lower()

    def test_keeps_clean_names(self):
        out = _safe_output_name("Preservation Manual.docx", "docx", sanitize=True)
        assert out == "Preservation Manual_clean.docx"
