"""
No-overclaim / no-hidden-metadata gate for the delivered DOCX.

A user-facing document must NOT contain AI-authorship disclosures or internal
evidence (quality scores, run ids, model slots, verdicts, manifests) unless the
caller explicitly opts in via include_ai_disclosure=True.

This gate scans every text-bearing part of the assembled DOCX:
core properties, body paragraphs, headings, table cells, and section
headers/footers.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

from ops.docgen.document_assembler_minimal import DocumentAssemblerMinimal
from ops.docgen.document_block_graph import (
    BlockType,
    DocumentBlock,
    DocumentBlockGraph,
)

# Case-insensitive substrings that must never appear in a delivered document.
FORBIDDEN_MARKERS = [
    "generated by ai",
    "generated by chatgpt",
    "ai-generated",
    "aims internal",
    "run_id",
    "model_slot",
    "baseline_score",
    "final_verdict",
    "evidence_manifest",
    # Internal block-quality evidence leak (the [Block quality: ...] paragraph).
    "block quality",
]


def _build_graph() -> DocumentBlockGraph:
    graph = DocumentBlockGraph(document_type="technical_report")
    for i in range(1, 4):
        block = DocumentBlock(
            block_id=f"SEC-{i:03d}",
            block_type=BlockType.SECTION,
            document_type="technical_report",
            required=True,
            generated_content=(
                f"Section {i} presents distinct engineering analysis and "
                f"specific findings for topic {i}. " * 25
            ),
            quality_score=0.91,
        )
        graph.blocks[f"SEC-{i:03d}"] = block
    return graph


def _all_docx_text(docx_path: Path) -> list[str]:
    """Collect text from every text-bearing part of the DOCX."""
    from docx import Document

    doc = Document(str(docx_path))
    texts: list[str] = []

    # Core properties (author, comments, subject, keywords, title, etc.)
    cp = doc.core_properties
    for attr in (
        "author",
        "comments",
        "subject",
        "category",
        "keywords",
        "title",
        "last_modified_by",
    ):
        value = getattr(cp, attr, None)
        if value:
            texts.append(str(value))

    # Body paragraphs (includes headings).
    texts.extend(p.text for p in doc.paragraphs)

    # Table cells.
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                texts.extend(p.text for p in cell.paragraphs)

    # Section headers/footers.
    for section in doc.sections:
        texts.extend(p.text for p in section.header.paragraphs)
        texts.extend(p.text for p in section.footer.paragraphs)

    return [t for t in texts if t]


def test_generated_docx_has_no_ai_or_internal_markers():
    """Default assembly (debug off, disclosure off) must contain no forbidden markers."""
    with tempfile.TemporaryDirectory() as tmpdir:
        assembler = DocumentAssemblerMinimal(_build_graph(), Path(tmpdir), strict=False)
        docx_path = assembler.assemble()
        assert docx_path is not None and docx_path.exists()

        texts = _all_docx_text(docx_path)
        haystack = "\n".join(texts).lower()

        for marker in FORBIDDEN_MARKERS:
            assert marker not in haystack, (
                f"Forbidden marker '{marker}' leaked into delivered DOCX. "
                f"Offending text: {[t for t in texts if marker in t.lower()]}"
            )


def test_default_assembly_has_no_disclosure_flag():
    """include_ai_disclosure must default to False."""
    with tempfile.TemporaryDirectory() as tmpdir:
        assembler = DocumentAssemblerMinimal(_build_graph(), Path(tmpdir))
        assert assembler.include_ai_disclosure is False


def test_opt_in_disclosure_appears_when_requested():
    """Positive control: with include_ai_disclosure=True the disclosure is present."""
    with tempfile.TemporaryDirectory() as tmpdir:
        assembler = DocumentAssemblerMinimal(
            _build_graph(), Path(tmpdir), include_ai_disclosure=True
        )
        docx_path = assembler.assemble()
        assert docx_path is not None and docx_path.exists()

        haystack = "\n".join(_all_docx_text(docx_path)).lower()
        assert "ai assistance" in haystack
