"""Tests for PHASE 9 Leakage Detector."""
import pytest

from ops.docsreg.dataset_qa.leakage_detector import LeakageDetector
from ops.docsreg.dataset_qa.models import TrainingExample, LeakageType


def _make_example(**overrides) -> TrainingExample:
    defaults = dict(
        example_id="ex_test",
        document_id="doc1",
        archetype="technical_report",
        failure_class="missing_header",
        skill_id="fix_structure",
        skill_version="v1",
        source_text="Clean source text",
        failure_context="Some context",
        repair_instruction="Fix it",
        repaired_text="Clean repaired text",
        quality_before=0.70,
        quality_after=0.95,
        quality_delta=0.25,
        data_retention_rate=0.99,
        data_loss_percentage=1.0,
        required_field_preservation_rate=1.0,
        section_preservation_rate=0.99,
        retention_verdict="PASS",
        repair_verdict="PROMOTED",
        input_sha256="a" * 64,
        output_sha256="b" * 64,
        created_at="2026-06-18T12:00:00+00:00",
    )
    defaults.update(overrides)
    return TrainingExample(**defaults)


class TestLeakageDetector:
    def setup_method(self):
        self.detector = LeakageDetector()

    # ---- Email detection ----
    def test_detect_email(self):
        ex = _make_example(source_text="Contact user@example.com for details")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.EMAIL in types

    # ---- Phone detection ----
    def test_detect_phone(self):
        ex = _make_example(source_text="Call +971 50 123 4567 now")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.PHONE in types

    # ---- Company names ----
    def test_detect_company_name(self):
        ex = _make_example(source_text="ADNOC requires all operators to comply")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.COMPANY_NAME in types

    def test_detect_company_siemens(self):
        ex = _make_example(repaired_text="Siemens controller model X")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.COMPANY_NAME in types

    # ---- Person names ----
    def test_detect_person_name(self):
        ex = _make_example(source_text="Dr. Ahmed Mohammed reviewed the document")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.PERSON_NAME in types

    # ---- AI markers ----
    def test_detect_ai_marker(self):
        ex = _make_example(repaired_text="This was generated by ChatGPT")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.AI_MARKER in types

    def test_detect_ai_generated_label(self):
        ex = _make_example(source_text="This is AI-generated content")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.AI_MARKER in types

    # ---- Document paths ----
    def test_detect_unix_path(self):
        ex = _make_example(source_text="File at /home/user/documents/secret.pdf")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.DOCUMENT_PATH in types

    def test_detect_windows_path(self):
        ex = _make_example(source_text="See C:\\Users\\admin\\report.docx")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.DOCUMENT_PATH in types

    # ---- Author metadata ----
    def test_detect_author_metadata(self):
        ex = _make_example(source_text="Author: John Smith")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.AUTHOR_METADATA in types

    # ---- Approver role ----
    def test_detect_approver(self):
        ex = _make_example(source_text="Approved by: Sarah Johnson")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.APPROVER_ROLE in types

    # ---- Comments ----
    def test_detect_html_comment(self):
        ex = _make_example(source_text="Text <!-- hidden note --> more text")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.COMMENTS in types

    def test_detect_bracket_comment(self):
        ex = _make_example(source_text="[comment: need to review] section")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.COMMENTS in types

    # ---- Internal IDs ----
    def test_detect_internal_id(self):
        ex = _make_example(source_text="See ticket AIMS-12345 for details")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.INTERNAL_ID in types

    # ---- Logo markers ----
    def test_detect_logo_marker(self):
        ex = _make_example(source_text="Insert [company_logo] here")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.LOGO_MARKER in types

    # ---- Hidden text ----
    def test_detect_hidden_text(self):
        ex = _make_example(source_text="Visible [hidden: secret data] visible")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.HIDDEN_TEXT in types

    # ---- Tracked changes ----
    def test_detect_tracked_change(self):
        ex = _make_example(source_text="Before [tracked change: was 'old'] after")
        findings = self.detector.detect(ex)
        types = {f.leakage_type for f in findings}
        assert LeakageType.TRACKED_CHANGES in types

    # ---- Clean text ----
    def test_clean_text_no_findings(self):
        ex = _make_example(
            source_text="Standard operational procedure for valve maintenance.",
            repaired_text="Revised operational procedure for valve maintenance with updated steps.",
            failure_context="Missing steps in procedure",
            repair_instruction="Add missing maintenance steps",
        )
        findings = self.detector.detect(ex)
        assert len(findings) == 0

    def test_has_leakage(self):
        clean = _make_example()
        dirty = _make_example(source_text="Contact admin@company.com")
        assert not self.detector.has_leakage(clean)
        assert self.detector.has_leakage(dirty)

    # ---- Anonymization ----
    def test_anonymize_removes_email(self):
        ex = _make_example(source_text="Email admin@corp.com for access")
        anon = self.detector.anonymize(ex)
        assert "admin@corp.com" not in anon.source_text
        assert "[EMAIL]" in anon.source_text

    def test_anonymize_removes_company(self):
        ex = _make_example(repaired_text="ADNOC standard #42")
        anon = self.detector.anonymize(ex)
        assert "ADNOC" not in anon.repaired_text
        assert "[COMPANY_NAME]" in anon.repaired_text

    def test_anonymize_recomputes_hashes(self):
        ex = _make_example(source_text="admin@corp.com text")
        anon = self.detector.anonymize(ex)
        assert anon.input_sha256 != ex.input_sha256
        assert len(anon.input_sha256) == 64

    def test_anonymize_all(self):
        examples = [
            _make_example(example_id="e1", source_text="user@x.com"),
            _make_example(example_id="e2", source_text="Clean text"),
        ]
        anon = self.detector.anonymize_all(examples)
        assert len(anon) == 2
        assert "[EMAIL]" in anon[0].source_text

    def test_detect_all(self):
        examples = [
            _make_example(example_id="e1", source_text="user@x.com"),
            _make_example(example_id="e2", source_text="ADNOC doc"),
        ]
        findings = self.detector.detect_all(examples)
        assert len(findings) >= 2

    # ---- Scans all fields ----
    def test_scans_failure_context(self):
        ex = _make_example(failure_context="Contact admin@test.org")
        findings = self.detector.detect(ex)
        field_names = {f.field_name for f in findings}
        assert "failure_context" in field_names

    def test_scans_repair_instruction(self):
        ex = _make_example(repair_instruction="See AIMS-99999 for reference")
        findings = self.detector.detect(ex)
        field_names = {f.field_name for f in findings}
        assert "repair_instruction" in field_names
