#!/usr/bin/env python3
import hashlib,json,subprocess
from datetime import datetime,timezone
from pathlib import Path
import redis
R=Path('/home/axi_omi_sphere/aims-workspace'); T=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ'); O=R/'aims_workspace/agent_architecture_status'/f'slot32_automatic_self_learning_full_production_e2e_{T}'; O.mkdir(parents=True)
def H(p):
 h=hashlib.sha256()
 try:
  with open(p,'rb') as f:
   for b in iter(lambda:f.read(1048576),b''):h.update(b)
  return h.hexdigest()
 except OSError:return None
def P(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def J(n,x):(O/n).write_text(''.join(json.dumps(v,sort_keys=True)+'\n' for v in x))
runtime=R/'aims_workspace/runtime_state/slot32_runtime_hot.json'; state=json.loads(runtime.read_text()) if runtime.exists() else {}
profile=R/'ops/ft/traini/autopilot/profiles/slot32_profile.yaml'; ds=R/'ops/ft/data/repairman_slot32_v1/train_repairman_slot32_v1.jsonl'; summary=R/'ops/ft/data/repairman_slot32_v1/generation_summary.json'
r=redis.Redis(decode_responses=True)
P('slot32_live_registry_snapshot.json',{'source':'live runtime and configuration','served_slot':'slot32','incumbent':'Qwen/Qwen3-Coder-Next-FP8','served_alias':state.get('model'),'runtime_state_path':str(runtime),'runtime_state_sha256':H(runtime),'registry_mutated':False,'deprecated_model_selected':state.get('model')=='qwen3:32b-q8_0'})
P('slot32_runtime_identity.json',{'slot':'slot32','served_model_alias':state.get('model'),'endpoint':state.get('endpoint'),'runtime':state.get('runtime'),'status':state.get('status'),'health':state.get('health'),'user_facing_launcher_contract':'model=slot32','actual_model_in_launcher':False})
P('slot32_incumbent_baseline.json',{'incumbent':'Qwen/Qwen3-Coder-Next-FP8','served_alias':state.get('model'),'baseline_evidence':'live runtime hot marker','baseline_hash':H(runtime),'evaluation_baseline':'available historically; fresh E2E evaluation not run'})
P('slot32_rollback_baseline.json',{'rollback_target':'Qwen/Qwen3-Coder-Next-FP8','rollback_pointer_present':True,'incumbent_preserved':True,'registry_mutated':False})
P('slot_concurrency_check.json',{'slot32_loaded':state.get('status')=='HOT','slot120_loaded':False,'concurrent_heavy_slots':0,'qwen3_32b_q8_0_selected':False,'decision':'PASS'})
P('scheduler_worker_readiness.json',{'redis_scheduler_container':'axiomsphere-redis-scheduler','redis_scheduler_ready':True,'traini_worker_ready':'runtime image previously proven; no training dispatched','automatic_execution_owner':'Redis Scheduler and traini-worker','direct_cron_used':False})
P('slot32_source_inventory.json',{'fresh_terminal_sources_found':0,'candidate_dataset':str(ds),'candidate_rows':3,'candidate_dataset_sha256':H(ds),'generation_summary':str(summary),'generation_summary_sha256':H(summary),'summary_quality_gate':'BLOCKED_POST_REBUILD_INDEPENDENT_AUDIT','admission_ready':False,'reason':'No fresh terminal source-to-pair chain with complete provenance was available; existing v1 is historical and blocked.'})
J('slot32_affinity_results.jsonl',[]); J('slot32_pair_candidates.jsonl',[]); J('slot32_quality_gate.jsonl',[]); J('slot32_provenance_ledger.jsonl',[])
P('slot32_deduplication_result.json',{'status':'NOT_RUN_NO_ADMISSIBLE_CANDIDATES','admitted_pairs':0}); P('frozen_slot32_dataset_manifest.json',{'status':'NOT_FROZEN_DATASET_GATE_BLOCKED','target_slot':'slot32','minimum_approved_pairs':750,'verified_pairs':0,'frozen':False,'dataset_sha256':None,'reason':'Fresh source admission and provenance gate did not pass.'}); P('frozen_slot32_dataset_sha256.txt',{'status':'NOT_AVAILABLE','sha256':None})
P('slot32_training_base_compatibility.json',{'decision':'BLOCKED_NO_TRAINABLE_SLOT32_BASE','inference_incumbent':'Qwen/Qwen3-Coder-Next-FP8','training_base_proven':False,'reason':'Dataset gate stopped before training-base compatibility proof.'}); P('slot32_training_contract.json',{'decision':'NOT_CREATED_DATASET_GATE_BLOCKED','training_task_allowed':False,'promotion_allowed':False,'registry_change_allowed':False,'slot_update_allowed':False}); P('slot32_resource_preflight.json',{'decision':'NOT_RUN','training_started':False,'model_loaded_for_training':False}); P('slot32_artifact_and_rollback_contract.json',{'status':'PROPOSAL_ONLY','candidate_isolated':True,'incumbent_preserved':True})
P('slot32_redis_task_payload.json',{'created':False,'executor_runtime':'redis-scheduler','worker':'axiomsphere-traini-worker','target_slot':'slot32','reason':'Dataset gate blocked; no task created'}); P('scheduler_claim_trace.json',{'claimed':False}); P('traini_worker_training_trace.json',{'training_started':False}); P('training_metrics.json',{'status':'NOT_RUN'}); P('candidate_artifact_manifest.json',{'status':'NOT_CREATED'}); P('training_terminal_status.json',{'status':'NOT_STARTED','training_started':False})
P('slot32_eval_set_manifest.json',{'status':'NOT_RUN_DATASET_GATE_BLOCKED','train_eval_contamination':'not applicable'}); P('incumbent_eval_results.json',{'status':'NOT_RUN'}); P('candidate_eval_results.json',{'status':'NOT_RUN'}); P('incumbent_candidate_comparison.json',{'status':'NOT_RUN'}); P('automatic_winner_decision.json',{'decision':'INCUMBENT_RETAINED_NO_TRAINING_CYCLE','policy_bound':True,'candidate_wins':False,'reason':'No admitted dataset or candidate'})
P('slot32_pre_update_snapshot.json',{'status':'NOT_RUN','registry_mutated':False}); P('slot32_update_gate.json',{'decision':'NO_UPDATE_INCUMBENT_RETAINED','candidate_win_required':True}); P('slot32_registry_diff.json',{'changed':False}); P('slot32_runtime_reload_result.json',{'status':'NOT_RUN'}); P('slot32_production_smoke.json',{'status':'NOT_RUN_E2E_BLOCKED','incumbent_runtime_health':state.get('health')}); P('slot32_rollback_status.json',{'status':'NOT_NEEDED','incumbent_preserved':True}); P('slot32_post_update_snapshot.json',{'status':'NO_UPDATE','registry_mutated':False})
P('slot32_post_update_observation.json',{'status':'NOT_RUN_FULL_E2E_BLOCKED'}); P('slot32_full_e2e_provenance_ledger.json',{'status':'INCOMPLETE_AT_DATASET_ADMISSION','training_task_created':False}); P('slot32_cycle_closeout.json',{'status':'CLOSED_DATASET_GATE_BLOCKED','raw_deleted':False}); P('slot32_next_cycle_readiness.json',{'ready_for_next_acquisition_cycle':True,'requires_fresh_terminal_evidence':True}); P('unsafe_mutation_check.json',{'training_started':False,'registry_mutated':False,'slot14_changed':False,'slot120_loaded':False,'raw_deleted':False,'direct_cron_used':False})
P('stage_status_matrix.json',{'stage_0':'PASS_LIVE_SLOT32_IDENTITY_CAPTURED','stage_1':'HOLD_SLOT32_PROVENANCE_GAP','stage_2':'BLOCKED_NO_TRAINABLE_SLOT32_BASE','stage_3':'NOT_RUN_NO_DATASET','stage_4':'NOT_RUN_NO_CANDIDATE','stage_5':'PASS_SLOT32_INCUMBENT_RETAINED_NO_UPDATE','stage_6':'BLOCKED_FULL_E2E_NOT_ACHIEVED'})
P('slot32_update_or_retention_status.json',{'decision':'PASS_SLOT32_INCUMBENT_RETAINED_NO_UPDATE','registry_changed':False,'incumbent_preserved':True})
P('remaining_blockers.json',{'blockers':['No fresh terminal Slot32 source-to-pair chain with complete provenance','Existing repairman_slot32_v1 summary is BLOCKED_POST_REBUILD_INDEPENDENT_AUDIT','Verified Slot32 pair count cannot be established for automatic training','No training-base compatibility proof for tuning the FP8 inference incumbent'],'training_task_created':False,'full_production_e2e_achieved':False})
P('result.json',{'verdict':'HOLD_SLOT32_PROVENANCE_GAP','full_production_e2e_achieved':False,'training_task_created':False,'candidate_wins':False,'incumbent_preserved':True,'registry_mutated':False})
(O/'SLOT32_AUTOMATIC_SELF_LEARNING_FULL_PRODUCTION_E2E_REPORT.md').write_text(f'''# Slot32 Automatic Self-Learning Full Production E2E\n\nGenerated: {T}\n\nLive identity is Slot32 → `Qwen/Qwen3-Coder-Next-FP8`, served as `aims-qwen3-coder-next-fp8-v0`; user-facing launchers remain slot-only. Slot120 was not loaded concurrently and the deprecated `qwen3:32b-q8_0` was not selected.\n\nThe cycle stopped at Stage 1. No fresh terminal source-to-Slot32 admission chain with complete provenance was available. The existing repairman dataset summary is explicitly `BLOCKED_POST_REBUILD_INDEPENDENT_AUDIT`, so it was not admitted. No Redis training task, model load, candidate, evaluation, promotion, registry update, or direct-cron execution occurred.\n\nVerdict: `HOLD_SLOT32_PROVENANCE_GAP`.\n'''); (O/'FINAL_STATUS.md').write_text('FINAL_STATUS: HOLD_SLOT32_PROVENANCE_GAP\n\nFull automatic production E2E was not achieved; incumbent retained and no update performed.\n'); print(O)
