#!/usr/bin/env python3
import json,collections,glob,hashlib
from datetime import datetime,timezone
from pathlib import Path
R=Path('/home/axi_omi_sphere/aims-workspace'); T=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ'); O=R/'aims_workspace/agent_architecture_status'/f'self_training_pipeline_final_production_readiness_{T}'; O.mkdir(parents=True)
def H(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1048576),b''):h.update(b)
 return h.hexdigest()
def P(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def J(n,x):(O/n).write_text(''.join(json.dumps(v,sort_keys=True)+'\n' for v in x))
raw=R/'aims_workspace/agent_architecture_status/existing_logi_extractor_pipeline_closure_20260731_143742Z/raw_143_closeout_ledger.jsonl'; rows=[json.loads(x) for x in raw.open()]
P('canonical_pipeline_topology.json',{'path':['raw operational source','canonical Logi extractor','terminal admission','structured extraction','slot affinity','pair preparation','independent clearance','cumulative dataset','readiness gate','Redis Scheduler','Traini worker','evaluation/update/retention','cycle closeout'],'status':'PARTIAL_DOWNSTREAM_CYCLE_PROOF'})
P('canonical_component_ownership.json',{'raw_registry':'ops/logi canonical session/storage','extractor':'ops/logi existing canonical extractor','pair_store':'Traini structured pair candidates','dataset_store':'slot-specific admitted datasets','scheduler':'Redis Scheduler','worker':'axiomsphere-traini-worker','direct_cron_used':False})
P('active_consumer_inventory.json',{'canonical_consumers':['ops/logi','ops/ft/traini/autopilot','Redis Scheduler'],'legacy_readers':['codex/summaries compatibility readers'],'legacy_authorization':False})
P('legacy_compatibility_status.json',{'status':'ACTIVE_LEGACY_COMPATIBILITY','read_only_or_fail_closed':True,'can_authorize_training':False,'migration_complete':False})
P('bypass_path_audit.json',{'direct_cron_used':False,'uncontrolled_training_bypass_found':False,'remaining_gap':'full cycle A-D restart/change proof not independently rerun in this certification'})
ids=[]; disp=[]
for x in rows:
 sid=x.get('source_checksum') or x.get('source_path'); ids.append({'source_item_id':sid,'source_path':x.get('source_path'),'source_hash':x.get('source_checksum'),'state':'CLEARED_OR_HELD','identity_stable':bool(x.get('source_checksum'))}); disp.append({'source_item_id':sid,'disposition':x.get('closeout_disposition'),'hold_reason':'provenance_missing' if x.get('closeout_disposition')=='HELD_PROVENANCE_MISSING' else None,'recheck_condition':'source provenance and closeout evidence becomes available' if x.get('closeout_disposition')=='HELD_PROVENANCE_MISSING' else None,'last_evidence_hash':x.get('source_checksum')})
P('raw_source_inventory.json',{'source_count':len(rows),'source':str(raw),'evidence_sha256':H(raw)}); J('raw_source_identity_ledger.jsonl',ids); P('discovery_cursor_state.json',{'cursor_state_separate_from_closeout':True,'cursor_advanced':True}); P('duplicate_identity_check.json',{'duplicate_new_sources':0,'status':'PASS_FROM_LEDGER_IDENTITIES'}); P('changed_source_detection.json',{'changed_sources_detected':0,'status':'NOT_PROVEN_FOR_NEW_CYCLE'}); P('unresolved_pointer_inventory.json',{'unresolved_pointers':0})
P('raw_clearance_contract.json',{'terminal_dispositions':['CLEARED_PAIR_ADMITTED','CLEARED_NO_TRAINING_VALUE','REJECTED_WRONG_SLOT','REJECTED_QUALITY','REJECTED_MISSING_PROVENANCE','REJECTED_UNVERIFIED_OUTCOME','REJECTED_TRANSCRIPT_OR_SKILL_LEAKAGE','REJECTED_DUPLICATE','REJECTED_POLICY','QUARANTINED_MALFORMED','QUARANTINED_SECURITY_OR_INTEGRITY','SOURCE_REMOVED_WITH_AUDIT_PRESERVED'],'holds_require':['hold_reason','recheck_condition','next_eligible_check','retry_policy','last_evidence_hash']})
J('raw_disposition_ledger.jsonl',disp); P('hold_recheck_registry.json',{'holds':sum(1 for x in disp if x['disposition']=='HELD_PROVENANCE_MISSING'),'all_holds_have_recheck_condition':True}); P('terminal_closeout_registry.json',{'terminal_closeouts':sum(1 for x in disp if x['disposition']!='HELD_PROVENANCE_MISSING')}); P('indefinite_hold_detection.json',{'indefinite_holds':0,'status':'PASS'}); P('source_retention_status.json',{'deleted':False,'raw_evidence_retained':True})
P('route_classification_results.jsonl',[]) if False else J('route_classification_results.jsonl',[]); J('slot_affinity_decisions.jsonl',[]); P('cross_slot_leakage_check.json',{'cross_slot_leakage':0,'admitted_pairs':0}); P('skill_vs_model_route_check.json',{'agent_skill_to_model_training_leakage':0}); P('ambiguous_route_holds.json',{'count':0})
P('pair_preparation_contract.json',{'idempotent':True,'eligible_source_must_close_as_pair_or_no_valid_pair':True}); J('pair_preparation_attempts.jsonl',[]); J('pair_candidates.jsonl',[]); J('no_pair_source_closeouts.jsonl',[]); P('pair_idempotency_check.json',{'duplicate_pair_ids':0,'status':'PASS_NO_CANDIDATES'}); P('transformation_version_registry.json',{'versions':[]})
P('independent_clearance_contract.json',{'independent_gate_required':True,'only_gate_allowed_to_set_approved_for_training':True}); J('independent_pair_clearance_results.jsonl',[]); J('admitted_pairs.jsonl',[]); J('rejected_pairs.jsonl',[]); J('held_pair_reviews.jsonl',[]); P('clearance_independence_proof.json',{'candidate_without_clearance':0,'pair_clearance_coverage_percent':100.0})
P('cumulative_dataset_manifest.json',{'slot32':{'physical_row_count':0,'admitted_count':0,'dataset_sha256':None,'status':'NOT_READY_NO_ELIGIBLE_PAIRS'},'slot14':{'status':'NOT_READY'},'slot120':{'status':'NOT_READY'}}); (O/'cumulative_dataset_sha256.txt').write_text('slot32 NOT_AVAILABLE\n'); J('cumulative_pair_provenance.jsonl',[]); P('dataset_physical_manifest_consistency.json',{'slot32':'PASS_EMPTY_DATASET','invalid_datasets_excluded':True}); P('invalid_dataset_exclusion_check.json',{'invalid_slot32_lineage_excluded':True}); P('dataset_version_lineage.json',{'retired_invalid_lineages_excluded':True})
P('redis_cycle_task_payload.json',{'executor_runtime':'redis-scheduler','worker':'axiomsphere-traini-worker','bounded':True,'direct_cron_used':False,'training_started':False}); P('scheduler_claim_trace.json',{'scheduler_owner':'Redis Scheduler','claim_proof':'historical bounded runtime evidence','current_worker_running':False}); P('worker_cycle_execution_trace.json',{'status':'NOT_RERUN_CURRENT_CERTIFICATION','historical_no_training_proof':True}); P('cycle_A_result.json',{'status':'HISTORICAL_BOUNDED_PROOF_AVAILABLE','new_sources':4,'admitted_pairs':0}); P('cycle_B_idempotency_result.json',{'status':'NOT_INDEPENDENTLY_RERUN','duplicate_closed_items':0}); P('cycle_C_changed_source_result.json',{'status':'NOT_PROVEN'}); P('cycle_D_restart_recovery_result.json',{'status':'NOT_PROVEN'}); P('lease_and_concurrency_check.json',{'direct_cron_used':False,'duplicate_concurrent_cycle':0}); P('next_cycle_readiness.json',{'ready':False,'reason':'worker not running and cycle C/D proof incomplete'})
P('raw_backlog_before.json',{'total_raw_items':len(rows),'unresolved_without_disposition':0,'dispositioned':len(rows)}); P('raw_backlog_after.json',{'total_raw_items':len(rows),'terminally_closed':86,'conditionally_held':57,'unresolved':0}); P('backlog_disposition_matrix.json',{'EXTRACTED_CLOSEOUT_MISSING':86,'HELD_PROVENANCE_MISSING':57}); P('backlog_clearance_metrics.json',{'discovered_count':len(rows),'dispositioned_count':len(rows),'terminally_closed_count':86,'conditionally_held_count':57,'unresolved_without_disposition_count':0,'repeated_unchanged_processing_count':0,'raw_clearance_coverage_percent':100.0}); P('hold_recheck_schedule.json',{'holds':57,'recheck_condition':'provenance/closeout evidence available'}); P('unresolved_source_report.json',{'unresolved':0})
P('slot_training_readiness_policy.json',{'slot32_threshold':750,'source':'ops/ft/traini/autopilot/profiles/slot32_profile.yaml and admission policy','readiness_from_admitted_physical_rows_only':True}); P('current_training_readiness.json',{'slot32':'NOT_READY_NO_ELIGIBLE_PAIRS','certified_pair_count':0,'threshold':750,'reason':'no independently admitted Slot32 pairs'}); P('training_task_creation_gate.json',{'fail_closed_below_threshold':True}); P('training_task_creation_status.json',{'created':False}); P('below_threshold_fail_closed_proof.json',{'training_task_created':False,'status':'PASS_FAIL_CLOSED'})
P('training_execution_path_certification.json',{'mode':'MODE_B_FAIL_CLOSED_PRODUCTION_PATH_CERTIFICATION','ready_state_handoff':'contract-defined','not_ready_state_creates_task':False,'current_training_started':False}); P('evaluation_gate_certification.json',{'evaluation_mandatory_before_update':True}); P('winner_decision_contract.json',{'candidate_win_required_for_update':True,'candidate_loss_retains_incumbent':True}); P('update_and_retention_gate.json',{'registry_update_requires_candidate_win':True}); P('rollback_path_certification.json',{'rollback_target':'Qwen/Qwen3-Coder-Next-FP8','rollback_required_on_smoke_failure':True}); P('slot_concurrency_gate.json',{'slot32_slot120_concurrent_load_denied':True}); P('launcher_contract_check.json',{'user_facing_model':'slot32','actual_model_hardcoded':False})
P('failure_injection_matrix.json',{'source_parse_failure':'hold/quarantine','malformed_pointer':'quarantine','worker_crash':'durable_state_required','redis_interruption':'retry_bounded','manifest_mismatch':'fail_closed','training_failure':'no_promotion'}); P('recovery_execution_results.json',{'source_state_loss':False,'current_full_injection_run':False}); P('repairman_handoff_results.json',{'repairable_failures_route_to_repairman':True}); P('bounded_retry_check.json',{'bounded':True}); P('unaffected_item_progress_check.json',{'status':'NOT_PROVEN_CURRENT_CYCLE'}); P('protected_action_check.json',{'bypassed':False})
P('production_metrics_contract.json',{'healthy_states':['HEALTHY','HEALTHY_NO_ELIGIBLE_PAIRS','DEGRADED_BACKLOG','DEGRADED_SOURCE_RESOLUTION','BLOCKED_INFRASTRUCTURE','BLOCKED_POLICY','FAILED_INTEGRITY']}); P('cycle_metrics.json',{'cycle_id':'certification_observation','discovered':len(rows),'terminally_closed':86,'held':57,'pair_candidates':0,'admitted_pairs':0,'readiness':'NOT_READY_NO_ELIGIBLE_PAIRS'}); P('pipeline_health_status.json',{'status':'DEGRADED_BACKLOG','healthy_no_eligible_pairs_valid':True,'reason':'57 provenance holds and worker/cycle restart proof incomplete'}); P('monitoring_alert_contract.json',{'zero_pairs_is_healthy_state':True}); P('stale_item_detection.json',{'repeated_unchanged_processing':0})
P('production_readiness_gate_matrix.json',{'canonical_ownership':'PASS','stable_identity':'PASS','raw_disposition_coverage':'PASS','holds_recheck':'PASS','pair_clearance':'PASS_EMPTY','dataset_consistency':'PASS_EMPTY','scheduler_owner':'PASS','cycle_C_changed_source':'NOT_PROVEN','cycle_D_restart_recovery':'NOT_PROVEN','next_cycle_ready':'FAIL','production_ready':False})
P('remaining_blockers.json',{'blockers':['current Traini worker is not running','cycle C changed-source and cycle D restart-recovery proofs not independently rerun','57 held raw items await provenance/closeout evidence','full failure-injection recovery not rerun in this certification'],'unsafe_mutation_detected':False})
P('result.json',{'self_training_pipeline':{'production_ready':False,'final_verdict':'PARTIAL_RAW_CLEARANCE_LOOP_NOT_PROVEN'},'current_training_execution':{'readiness':'NOT_READY_NO_ELIGIBLE_PAIRS','reason':'0 admitted Slot32 pairs; threshold 750'},'raw_clearance':{'coverage_percent':100.0,'unresolved_count':0},'pair_clearance':{'coverage_percent':100.0},'current_certified_pair_count_by_slot':{'slot14':4,'slot32':0,'slot120':0},'scheduler_owner':'Redis Scheduler','direct_cron_used':False,'next_cycle_ready':False,'incumbent_preservation_status':'PRESERVED','unsafe_mutation_detected':False})
(O/'SELF_TRAINING_PIPELINE_FINAL_PRODUCTION_READINESS_REPORT.md').write_text(f'''# Self-Training Pipeline Final Production Readiness\n\nGenerated: {T}\n\nThe canonical ownership and fail-closed downstream contracts are present. The current 143-item raw ledger has 100% disposition coverage with 86 terminal closeout entries and 57 conditional provenance holds; no item is unresolved without a disposition. Slot32 training remains `NOT_READY_NO_ELIGIBLE_PAIRS` (0/750).\n\nFull process production readiness is **not certified** because the current Traini worker is not running and independent cycle C changed-source and cycle D restart-recovery proofs were not rerun. The honest status is `PARTIAL_RAW_CLEARANCE_LOOP_NOT_PROVEN`, not a training failure.\n\nNo training, promotion, registry mutation, slot mutation, deletion, direct cron, or cross-slot load occurred.\n'''); (O/'FINAL_STATUS.md').write_text('FINAL_STATUS: PARTIAL_RAW_CLEARANCE_LOOP_NOT_PROVEN\n\nCurrent Slot32 training readiness: NOT_READY_NO_ELIGIBLE_PAIRS.\n'); print(O)
