#!/usr/bin/env python3
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
R=Path('/home/axi_omi_sphere/aims-workspace'); T=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ'); O=R/'aims_workspace/agent_architecture_status'/f'slot32_provenance_recovery_independent_certification_{T}'; O.mkdir(parents=True)
def H(p):
 h=hashlib.sha256()
 try:
  with open(p,'rb') as f:
   for b in iter(lambda:f.read(1048576),b''):h.update(b)
  return h.hexdigest()
 except OSError:return None
def P(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def J(n,x):(O/n).write_text(''.join(json.dumps(v,sort_keys=True)+'\n' for v in x))
ds=R/'ops/ft/data/repairman_slot32_v1/train_repairman_slot32_v1.jsonl'; sm=R/'ops/ft/data/repairman_slot32_v1/generation_summary.json'; src=R/'aims_workspace/agent_architecture_status/qwen3_coder_30b_a3b_candidate_eval_20260715T195500Z/adjudication.json'; rows=[json.loads(x) for x in ds.read_text().splitlines() if x.strip()]
P('existing_slot32_dataset_inventory.json',{'dataset_path':str(ds),'row_count':len(rows),'dataset_sha256':H(ds),'generation_summary_path':str(sm),'generation_summary_sha256':H(sm),'generation_summary_declared_total_source_rows':5316,'generation_summary_declared_approved_pairs':1095,'generation_summary_quality_gate':'BLOCKED_POST_REBUILD_INDEPENDENT_AUDIT','generation_summary_negative_transfer_gate':'UNPROVEN_SELF_ASSERTED_TRANSFORMATION_FLAG','source_records':[{'path':str(src),'sha256':H(src),'status':'FAIL_QUALITY_GATE','case_count':3,'cases_passed':1,'cases_failed':1,'cases_inconclusive':1}],'transformation_records':'embedded metadata only; no independent transformation ledger','quality_outputs':'generation summary plus embedded codex_cli_audit; no independent admission output','audit_blockers':['self-referential source dataset list','declared approved count 1095 conflicts with physical row count 3','approved_for_training=false on every inspected row','source adjudication FAIL_QUALITY_GATE','negative_transfer_gate UNPROVEN_SELF_ASSERTED_TRANSFORMATION_FLAG','no per-row verification result linking repair execution to PASS']})
P('blocked_audit_gate_analysis.json',{'decision':'BLOCKED_POST_REBUILD_INDEPENDENT_AUDIT','failed_gates':[{'gate':'quality','evidence':'adjudication status FAIL_QUALITY_GATE','cause':'evidence absence'},{'gate':'negative transfer','evidence':'UNPROVEN_SELF_ASSERTED_TRANSFORMATION_FLAG','cause':'evidence absence'},{'gate':'admission','evidence':'approved_for_training false on rows','cause':'evidence absence'},{'gate':'count/manifest consistency','evidence':'1095 declared vs 3 physical rows','cause':'stale_or_inconsistent_manifest'}],'deterministic_repairs_allowed':['none without rewriting historical evidence'],'waiver_applied':False})
cls=[]; aff=[]; qual=[]; held=[]
for i,r in enumerate(rows):
 m=r.get('metadata',{}); audit=m.get('codex_cli_audit',{}); neg=m.get('negative_transfer',{}); c='MISSING_VERIFICATION'
 if m.get('target_slot')!='slot32': c='WRONG_SLOT'
 elif m.get('approved_for_training') is not True: c='MISSING_VERIFICATION'
 cls.append({'row_index':i,'classification':c,'target_slot':m.get('target_slot'),'source_dataset':m.get('source_dataset'),'source_hash':m.get('source_hash'),'source_id_present':bool(m.get('source_dataset')),'source_sha256_present':bool(m.get('source_hash')),'verification_result_present':False,'audit_status':audit.get('status'),'negative_transfer_status':neg.get('status'),'admission_decision':m.get('approved_for_training'),'reason':'Embedded audit is not an independent source-to-repair-to-verification record; approved_for_training is false.'})
 aff.append({'row_index':i,'target_slot':m.get('target_slot'),'decision':'HOLD_MISSING_VERIFICATION','slot32_affinity':m.get('target_slot')=='slot32'})
 qual.append({'row_index':i,'decision':'HOLD_MISSING_VERIFICATION','quality_score':None,'quality_gate':'FAIL_QUALITY_GATE_OR_UNPROVEN_TRANSFORMATION'})
 held.append({'row_index':i,'status':'HELD','reason':'No independently verified repair outcome and no approved_for_training admission'})
J('per_pair_provenance_classification.jsonl',cls); J('independent_affinity_results.jsonl',aff); J('independent_quality_gate_results.jsonl',qual); J('rejected_held_rows.jsonl',held); J('certified_slot32_pairs.jsonl',[]); J('certified_slot32_provenance_ledger.jsonl',[])
P('certified_slot32_dataset_manifest.json',{'status':'NO_CERTIFIED_DATASET','target_slot':'slot32','certified_pair_count':0,'minimum_approved_pairs':750,'dataset_sha256':None,'frozen':False,'reason':'All physical rows held for missing independent verification.'}); (O/'certified_slot32_dataset_sha256.txt').write_text('NOT_AVAILABLE\n')
P('independent_deduplication_result.json',{'status':'NOT_ADMISSIBLE','exact_duplicates':None,'near_duplicates':'not used to infer provenance','certified_pairs':0}); P('contamination_and_leakage_check.json',{'cross_slot_leakage':0,'agent_skill_leakage':0,'transcript_leakage':0,'deprecated_model_contamination':0,'status':'NO_ADMITTED_ROWS','note':'No rows admitted; absence of leakage among admitted rows does not certify held rows.'})
P('slot32_threshold_authority_decision.json',{'decision':'PASS_SLOT32_THRESHOLD_DISCOVERED','minimum_approved_pairs':750,'sources':['ops/ft/traini/autopilot/profiles/slot32_profile.yaml','ops/ft/traini/autopilot/policies/dataset_admission_policy.yaml','ops/ft/traini/autopilot/policies/dataset_policy.yaml'],'slot14_threshold_not_reused':True})
P('final_certified_pair_count.json',{'certified_existing':0,'recoverable_deterministically':0,'dataset_level_only_or_held':len(rows),'certified_total':0,'authoritative_minimum':750}); P('remaining_pair_gap.json',{'certified_count':0,'minimum_required':750,'remaining_gap':750}); P('slot32_dataset_readiness_decision.json',{'decision':'HOLD_SLOT32_PROVENANCE_GAP','certified_pairs':0,'minimum_required':750,'training_allowed':False,'fresh_acquisition_required':True})
P('training_task_creation_status.json',{'created':False,'task_key':None,'reason':'Independent certification failed at provenance/verification gates'}); P('incumbent_preservation_status.json',{'incumbent':'Qwen/Qwen3-Coder-Next-FP8','served_alias':'aims-qwen3-coder-next-fp8-v0','registry_mutated':False,'slot_launcher':'model=slot32'})
P('remaining_blockers.json',{'blockers':['physical dataset count conflicts with generation summary declared count','all inspected rows lack independently verified repair outcome','source adjudication FAIL_QUALITY_GATE','negative transfer transformation evidence unproven','certified count 0/750'],'training_task_created':False,'raw_deleted':False})
P('stage_status_matrix.json',{'dataset_inventory':'PASS','audit_gate_analysis':'PASS_BLOCKERS_CONFIRMED','per_pair_classification':'PASS_ROWS_HELD','independent_certification':'HOLD_PROVENANCE_GAP','threshold':'PASS_750_POLICY','training':'NOT_RUN'})
P('result.json',{'verdict':'HOLD_SLOT32_PROVENANCE_GAP','certified_pairs':0,'minimum_required':750,'remaining_gap':750,'training_task_created':False,'incumbent_preserved':True,'dataset_mutated':False})
(O/'SLOT32_PROVENANCE_RECOVERY_CERTIFICATION_REPORT.md').write_text(f'''# Slot32 Provenance Recovery and Independent Certification\n\nGenerated: {T}\n\nThe physical dataset `{ds}` contains {len(rows)} rows, while its generation summary declares 1,095 approved pairs from 5,316 source rows. This inconsistency is an independent audit blocker. The source adjudication is `FAIL_QUALITY_GATE`; the transformation gate is `UNPROVEN_SELF_ASSERTED_TRANSFORMATION_FLAG`; and each inspected row has `approved_for_training=false`.\n\nNo row was independently certified. Certified count is 0/750, so fresh terminal source acquisition is required. The incumbent `Qwen/Qwen3-Coder-Next-FP8` and `model=slot32` launcher contract were preserved. No training task, model load, evaluation, candidate build, promotion, registry change, or slot mutation occurred.\n\nVerdict: `HOLD_SLOT32_PROVENANCE_GAP`.\n'''); (O/'FINAL_STATUS.md').write_text('FINAL_STATUS: HOLD_SLOT32_PROVENANCE_GAP\n\nNo Slot32 rows independently certified; no training task created.\n'); print(O)
