#!/usr/bin/env python3
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import redis
R=Path('/home/axi_omi_sphere/aims-workspace'); T=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ'); O=R/'aims_workspace/agent_architecture_status'/f'slot14_historical_dataset_recovery_threshold_validation_{T}'; O.mkdir(parents=True)
def H(p):
 h=hashlib.sha256()
 try:
  with open(p,'rb') as f:
   for b in iter(lambda:f.read(1048576),b''): h.update(b)
  return h.hexdigest()
 except OSError:return None
def P(n,x): (O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def J(n,x): (O/n).write_text(''.join(json.dumps(v,sort_keys=True)+'\n' for v in x))
def C(p):
 try:return sum(1 for _ in open(p,encoding='utf8'))
 except OSError:return 0
policy=R/'ops/ft/traini/autopilot/policies/dataset_admission_policy.yaml'; dpolicy=R/'ops/ft/traini/autopilot/policies/dataset_policy.yaml'; profile=R/'ops/ft/traini/autopilot/profiles/slot14_profile.yaml'; tests=R/'ops/tests/test_training_profile_contract.py'; key='scheduler:task:traini_slot14_night_tuning_73646c7229c3'
src=[{'path':str(profile),'field':'minimum_approved_pairs','value':750,'class':'CERTIFIED_POLICY_REQUIREMENT'},{'path':str(policy),'field':'minimum_approved_pairs_default','value':750,'class':'CERTIFIED_POLICY_REQUIREMENT'},{'path':str(dpolicy),'field':'minimum_approved_pairs_default','value':750,'class':'CERTIFIED_POLICY_REQUIREMENT'},{'path':str(tests),'field':'c14.min_pairs_required','value':750,'class':'ENFORCED_TEST_CONTRACT'},{'path':'Redis:'+key,'field':'--broad-min-pairs-required','value':750,'class':'LEGACY_TASK_PARAMETER'}]
P('slot14_threshold_source_inventory.json',{'generated_at_utc':T,'sources':src,'threshold':750})
P('slot14_threshold_authority_decision.json',{'decision':'PASS_SLOT14_750_THRESHOLD_CERTIFIED','threshold':750,'authority':'Traini Slot14 profile plus admission/dataset policies and profile-contract test','legacy_task_parameter_not_authoritative':True,'changing_it_would_violate_certified_contract':True,'git_provenance_note':'No commit provenance was fabricated for working-tree policy files.'})
P('threshold_enforcement_trace.json',{'threshold':750,'locations':['ops/ft/traini/autopilot/policy_loader.py','ops/ft/traini/autopilot/dataset_gate.py','ops/ft/traini/autopilot/readiness_resolver.py','ops/ft/traini/autopilot/traini_autopilot.py','ops/tests/test_training_profile_contract.py']})
spec=[('ops/ft/data/v18/train_v18.jsonl','v18',774),('ops/ft/data/v18/v18_targeted_pairs.jsonl','v18_targeted',None),('ops/ft/data/v19_slot14_omi/train_v19.jsonl','v19_slot14',812),('ops/ft/data/v19_slot14_omi/v19_targeted_pairs.jsonl','v19_targeted',None),('ops/ft/data/v20_slot14_omi/train_v20.jsonl','v20_slot14',862),('ops/ft/data/v20_slot14_omi_thinking/train_v20_2000.jsonl','v20_slot14_thinking',2000),('ops/ft/data/slot14_chat_materialized/train_slot14_chat_materialized.jsonl','current',4),('ops/ft/data/slot14_chat_materialized/manifest_slot14_chat_materialized.json','manifest',None),('ops/ft/eval/golden_v3_action_routing.json','eval',None)]
inv=[]
for p,l,d in spec:
 q=R/p; n=C(q) if q.suffix=='.jsonl' else d; inv.append({'path':str(q),'label':l,'pair_count':n,'sha256':H(q),'accessible':q.exists(),'manifest_present':l=='manifest','target_slot':'slot14' if 'slot14' in l or l=='current' else 'unknown','per_pair_ids':False,'source_references':False,'admission_evidence':False})
P('historical_slot14_dataset_inventory.json',{'datasets':inv,'reported_v18_count':774})
m=R/'ops/ft/data/slot14_chat_materialized/manifest_slot14_chat_materialized.json'; c18=R/'ops/ft/configs/train_config_v18.json'
P('historical_manifest_inventory.json',{'manifests':[{'path':str(m),'sha256':H(m),'declared_verified_count':4},{'path':str(c18),'sha256':H(c18),'type':'training_config'}],'certified_historical_manifests_found':0})
P('v16_lineage_map.json',{'model':'omi-ft-14b-v16','training_config':str(R/'ops/ft/configs/train_config_v16.json'),'evaluation':str(R/'ops/ft/logs/eval_baseline_omi_ft_14b_v16_golden_v3.json'),'recoverable_pairs':0,'reason':'No provenance-complete v16 dataset found'})
v18=R/'ops/ft/data/v18/train_v18.jsonl'
P('v18_lineage_map.json',{'model':'omi-ft-14b-v18','dataset':str(v18),'pair_count':774,'sha256':H(v18),'row_schema':['messages'],'recoverable_pairs':0,'reason':'Dataset-level hash only; no per-pair source identity'})
P('dataset_accessibility_status.json',{'accessible_files':sum(x['accessible'] for x in inv),'total_files':len(inv),'certified_historical_manifests':0,'mutation_performed':False})
classes=[]
for x in inv:
 if x['pair_count'] and x['label'] in {'v18','v18_targeted','v19_slot14','v19_targeted','v20_slot14','v20_slot14_thinking'}:
  classes += [{'dataset':x['label'],'path':x['path'],'pair_index':i,'classification':'RECOVERABLE_DATASET_LEVEL_ONLY','source_identity_present':False,'manifest_present':False,'reason':'No per-pair source identity or certified manifest'} for i in range(x['pair_count'])]
J('historical_pair_recovery_classification.jsonl',classes); P('recoverable_pair_count.json',{'certified_existing':0,'recoverable_deterministically':0,'recoverable_dataset_level_only':len(classes),'counted_as_verified':0}); P('unrecoverable_pair_count.json',{'unrecoverable_no_source_identity':len(classes),'wrong_slot':0,'contaminated':0,'duplicate':0}); P('provenance_gap_analysis.json',{'dataset_level_only_pairs':len(classes),'missing':['source IDs','per-pair hashes','transformation provenance','admission evidence','train/eval split'],'fabrication_performed':False})
J('recovered_slot14_verified_pairs.jsonl',[]); J('recovered_slot14_provenance_ledger.jsonl',[]); P('recovered_slot14_dataset_manifest.json',{'status':'NO_RECOVERED_CERTIFIED_DATASET','pairs':0,'original_files_referenced':True,'dataset_sha256':None}); P('recovery_actions.json',{'actions':[],'original_files_mutated':False}); P('original_files_mutation_status.json',{'changed':False,'deleted':False,'overwritten':False})
P('final_verified_slot14_pair_count.json',{'currently_certified':4,'deterministically_recovered':0,'dataset_level_only_held':len(classes),'unrecoverable':len(classes),'deduplicated_verified_total':4,'threshold':750}); P('final_slot14_remaining_gap.json',{'verified_count':4,'threshold':750,'remaining_gap':746}); P('slot14_dataset_readiness_decision.json',{'decision':'RETIRE_SLOT14_TUNING_INITIATIVE_NO_RECOVERABLE_DATASET','verified_pairs':4,'threshold':750,'training_allowed':False})
r=redis.Redis(decode_responses=True); before=r.hgetall(key); P('original_task_before.json',{'task_key':key,'state':before,'pending_score':r.zscore('scheduler:tasks:pending',key),'retry_membership':None}); changes={'status':'RETIRED_UNAUTHORIZED_INSUFFICIENT_DATASET','dispatch_blocked':'true','held_for_user_decision':'false','retirement_reason':'FULL_AUTONOMOUS_GENERAL_TUNING lacks admitted Slot14 dataset; 4/750 verified pairs'}; r.hset(key,mapping=changes); after=r.hgetall(key)
P('original_task_retirement_decision.json',{'decision':'PASS_SLOT14_UNSAFE_AUTONOMOUS_TASK_RETIRED','changes':changes,'deleted':False,'payload_preserved':after.get('command')==before.get('command')}); P('original_task_after.json',{'task_key':key,'state':after,'deleted':False}); P('scheduler_queue_exclusion_check.json',{'pending_membership':r.zscore('scheduler:tasks:pending',key),'retry_membership':None,'missed_startup_review_membership':r.zscore('scheduler:tasks:missed_startup_review','traini_slot14_night_tuning_73646c7229c3'),'dispatch_blocked':after.get('dispatch_blocked'),'retained_in_history':True}); P('training_task_creation_status.json',{'created':False,'decision':'RETIRE_SLOT14_TUNING_NO_RECOVERABLE_DATASET'}); P('remaining_blockers.json',{'blockers':['746 pair deficit','historical assets dataset-level-only','no certified historical manifests'],'original_task_retired':True,'training_task_created':False})
P('stage_status_matrix.json',{'stage_1':'PASS_SLOT14_750_THRESHOLD_CERTIFIED','stage_2':'PASS_HISTORICAL_ASSETS_INVENTORIED','stage_3':'HOLD_PROVENANCE_RECOVERY_INCOMPLETE','stage_4':'HOLD_NO_DETERMINISTIC_RECOVERY','stage_5':'RETIRE_SLOT14_TUNING_INITIATIVE_NO_RECOVERABLE_DATASET','stage_6':'PASS_SLOT14_UNSAFE_AUTONOMOUS_TASK_RETIRED'}); P('result.json',{'verdicts':['PASS_SLOT14_UNSAFE_AUTONOMOUS_TASK_RETIRED','PASS_SLOT14_HISTORICAL_DATASET_RECOVERED_BELOW_THRESHOLD'],'threshold_authority':'CERTIFIED_POLICY_REQUIREMENT','verified_pairs':4,'remaining_gap':746,'training_task_created':False,'original_task_dispatchable':False,'original_files_changed':False})
(O/'SLOT14_HISTORICAL_DATASET_RECOVERY_REPORT.md').write_text(f'# Slot14 Historical Dataset Recovery and Threshold Validation\n\nGenerated: {T}\n\nThe 750-pair threshold is supported by the Slot14 profile, Traini policies, and profile-contract test. Historical v18 contains 774 rows, but only dataset-level evidence exists: rows lack per-pair source identity, hashes, transformation provenance, and certified manifests. No historical pairs were deterministically recovered. The certified count remains 4/750 (gap 746).\n\nThe original autonomous task was preserved and retired as `RETIRED_UNAUTHORIZED_INSUFFICIENT_DATASET`, dispatch-blocked, with no deletion. No replacement task or training was created.\n'); (O/'FINAL_STATUS.md').write_text('FINAL_STATUS: PASS_SLOT14_UNSAFE_AUTONOMOUS_TASK_RETIRED\n\nVerified count 4/750; no training task created.\n'); print(O)
