"""AIMS Self-test capability catalog (v1)."""
from __future__ import annotations

from typing import Any


def build_self_test_catalog() -> list[dict[str, Any]]:
    """Return machine-readable catalog of self-test capabilities."""
    return [
        {
            "test_id": "T001_autonomous_launch_suite",
            "name": "Autonomous Launch Suite",
            "owner_agent": "logi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/autonomous_launch/run_autonomous_launch.py",
            "expected_duration": "10-20m",
            "safe_for_daytime": False,
            "preferred_window": "22:30-06:30 Asia/Dubai",
            "resource_policy": "No slot120 force-load; obey DGX slot policy.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/autonomous_launch/*"],
            "pass_criteria": "All phases PASS.",
            "fail_criteria": "Any phase FAIL.",
            "corrective_owner": "logi",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": False,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T002_control_plane_smoke",
            "name": "Autonomy Control Plane v1 smoke",
            "owner_agent": "logi",
            "command_or_callable": "ops.logi.process_integrity_orchestrator._control_plane_smoke()",
            "expected_duration": "<1m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Readiness only; no destructive actions.",
            "required_env_vars": [],
            "expected_artifacts": ["aims_workspace/autonomy_control/ledgers/*/task_ledger.json"],
            "pass_criteria": "Latest v1 cert PASS/CERTIFIED and ledger smoke PASS.",
            "fail_criteria": "Missing cert evidence or ledger mismatch.",
            "corrective_owner": "logi",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T003_logi_integrity_cert",
            "name": "Logi Process Integrity certification",
            "owner_agent": "logi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/logi_process_integrity_certification.py",
            "expected_duration": "5-15m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No destructive actions; bounded retries.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/logi_process_integrity/certifications/*"],
            "pass_criteria": "6/6 scenarios PASS.",
            "fail_criteria": "Any scenario FAIL.",
            "corrective_owner": "logi",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": False,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T004_long_running_harness_smoke",
            "name": "Long-running self-regulation harness smoke",
            "owner_agent": "logi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/long_running_self_regulation_certification.py --mode smoke --cycles 3",
            "expected_duration": "2-10m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No 24h/72h start by default.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/long_running_self_regulation/certifications/*"],
            "pass_criteria": "3 cycles complete, no active blockers.",
            "fail_criteria": "Incomplete cycles or blocker.",
            "corrective_owner": "logi",
            "severity_if_fail": "PARTIAL",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T005_strategic_planned_actions",
            "name": "Strategic Planned Actions certification",
            "owner_agent": "logi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/strategic_planned_actions_certification.py",
            "expected_duration": "5-15m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Dry-run/live-lightweight only unless approved.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/strategic_planning/certifications/*"],
            "pass_criteria": "Certification PASS/PARTIAL with controlled risk notes.",
            "fail_criteria": "Critical scenario FAIL.",
            "corrective_owner": "logi",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": False,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T006_gstack_integration_audit",
            "name": "Gstack agent integration audit",
            "owner_agent": "argus",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/gstack_agent_integration_audit.py --run-id <id>",
            "expected_duration": "1-3m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Read-only integration checks.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/evals/gstack_agent_integration_audit/*"],
            "pass_criteria": "14/14 integrated, active stale refs=0.",
            "fail_criteria": "Missing integration or stale active refs.",
            "corrective_owner": "argus",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T007_stability_audit",
            "name": "Post-restart service stability audit",
            "owner_agent": "argus",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/post_restart_service_stability_audit.py --run-id <id>",
            "expected_duration": "1-3m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Lifecycle policy aware; no forced restart.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/evals/post_restart_service_stability_audit/*"],
            "pass_criteria": "overall_health ok/warn with no active blockers.",
            "fail_criteria": "active blockers detected.",
            "corrective_owner": "argus",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T008_dgx_concurrency_policy",
            "name": "DGX model concurrency policy smoke",
            "owner_agent": "argus",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/dgx_model_concurrency_policy_smoke.py --run-id <id>",
            "expected_duration": "<1m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "slot32 and slot120 must never be loaded together.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["aims_workspace/evals/dgx_model_concurrency_policy_smoke/*"],
            "pass_criteria": "status pass; no slot conflict.",
            "fail_criteria": "slot32/slot120 conflict or status fail.",
            "corrective_owner": "argus",
            "severity_if_fail": "CRITICAL",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T009_knomi_smoke",
            "name": "Knomi runtime skill smoke",
            "owner_agent": "knomi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/knomi_runtime_skill_smoke.py",
            "expected_duration": "1-2m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Read-only search checks.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["stdout summary / eval artifacts"],
            "pass_criteria": "No runtime error; expected query path usable.",
            "fail_criteria": "service unreachable or failed smoke.",
            "corrective_owner": "knomi",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T010_doci_smoke",
            "name": "Doci/DocAgent dry-run smoke",
            "owner_agent": "doci",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/doci_runtime_skill_smoke.py",
            "expected_duration": "1-3m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "Dry-run only.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["stdout summary / smoke report"],
            "pass_criteria": "No critical failure.",
            "fail_criteria": "doc pipeline unavailable.",
            "corrective_owner": "doci",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T011_omi_anonymization",
            "name": "Omi registry/anonymization smoke",
            "owner_agent": "omi",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/omi_runtime_skill_smoke.py",
            "expected_duration": "1-3m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No destructive registry mutation.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["stdout summary / smoke report"],
            "pass_criteria": "Runtime smoke pass/warn only.",
            "fail_criteria": "critical runtime failure.",
            "corrective_owner": "omi",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T012_traini_readiness",
            "name": "Traini learning/eval readiness smoke",
            "owner_agent": "traini",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/traini_runtime_skill_smoke.py",
            "expected_duration": "1-2m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No heavy training auto-start.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["stdout summary / smoke report"],
            "pass_criteria": "Traini service responds and smoke passes.",
            "fail_criteria": "service down or smoke fail.",
            "corrective_owner": "traini",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T013_telegram_delivery",
            "name": "Telegram delivery record check",
            "owner_agent": "logi",
            "command_or_callable": "inspect delivery events in ProcessLedger",
            "expected_duration": "<1m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No token exposure.",
            "required_env_vars": ["TELEGRAM_BOT_TOKEN", "OWNER_CHAT_IDS"],
            "expected_artifacts": ["telegram_delivery_record.json"],
            "pass_criteria": "PASS delivery or explicit fallback record.",
            "fail_criteria": "No delivery record at all.",
            "corrective_owner": "argus",
            "severity_if_fail": "PARTIAL",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T014_cloud_teacher_route",
            "name": "Cloud teacher route check",
            "owner_agent": "argus",
            "command_or_callable": "ops.logi.process_integrity_orchestrator._cloud_teacher_route_check()",
            "expected_duration": "<1m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "No token value logging.",
            "required_env_vars": ["OMNIROUTE_BASE_URL", "OMNIROUTE_MODEL", "OMNI_TOKEN"],
            "expected_artifacts": ["cloud route check in logi result"],
            "pass_criteria": "Route reachable and response keys present.",
            "fail_criteria": "Unreachable route for required test path.",
            "corrective_owner": "argus",
            "severity_if_fail": "PARTIAL",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T015_scheduler_health",
            "name": "Scheduler/planned action runner health check",
            "owner_agent": "scheduler",
            "command_or_callable": "PYTHONPATH=ops python3 ops/logi/planned_action_runner.py --mode dry-run --run-due",
            "expected_duration": "1-3m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "dry-run only by default.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": ["scheduled_actions/evidence/*", "runner summary"],
            "pass_criteria": "Runner executes without critical error.",
            "fail_criteria": "Runner crash or unsafe action execution.",
            "corrective_owner": "logi",
            "severity_if_fail": "WARN",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T016_secret_scan",
            "name": "Secret safety scan",
            "owner_agent": "security",
            "command_or_callable": "rg secret patterns in produced evidence",
            "expected_duration": "<1m",
            "safe_for_daytime": True,
            "preferred_window": "any",
            "resource_policy": "scan only; no content exfiltration.",
            "required_env_vars": [],
            "expected_artifacts": ["evidence/secret_scan.txt"],
            "pass_criteria": "No secret values in outputs.",
            "fail_criteria": "Token/key value exposure.",
            "corrective_owner": "security",
            "severity_if_fail": "CRITICAL",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
        {
            "test_id": "T014_repairman_auto_repair_loop",
            "name": "Repairman Automatic Repair & Retry Loop v1 certification",
            "owner_agent": "repairman",
            "command_or_callable": "PYTHONPATH=ops python3 ops/evals/repairman_automatic_repair_loop_certification.py",
            "expected_duration": "3-10m",
            "safe_for_daytime": False,
            "preferred_window": "22:30-06:30 Asia/Dubai",
            "resource_policy": "No destructive actions; no model promotion; no forced slot120 load; no slot32/slot120 conflict.",
            "required_env_vars": ["PYTHONPATH"],
            "expected_artifacts": [
                "aims_workspace/repairman_auto_repair/certifications/repairman_auto_repair_v1_*/repairman_auto_repair_result.json",
                "aims_workspace/repairman_auto_repair/certifications/repairman_auto_repair_v1_*/repairman_auto_repair_report.md",
                "aims_workspace/repairman_auto_repair/certifications/repairman_auto_repair_v1_*/repair_training_pairs_written.json",
                "aims_workspace/repairman_auto_repair/certifications/repairman_auto_repair_v1_*/lessons_learned_summary.json",
                "aims_workspace/repairman_auto_repair/certifications/repairman_auto_repair_v1_*/final_audits.json",
            ],
            "pass_criteria": "Repair policy, controlled failure+repair+retry, retry cap=5, training pairs/lessons, and final audits PASS/WARN historical-only.",
            "fail_criteria": "forbidden repair executed, retry cap missing, secret exposure, active blocker, or slot32/slot120 conflict.",
            "corrective_owner": "logi",
            "severity_if_fail": "BLOCKER",
            "can_run_in_smoke": True,
            "can_run_in_nightly": True,
            "can_run_in_24h": True,
            "can_run_in_72h": True,
        },
    ]
